In [48]:
from flask import Flask, jsonify, render_template, request
from pyspark.sql import SparkSession
from sklearn.pipeline import Pipeline
import pandas as pd
import numpy as np

In [49]:
arr = np.array(
    [
        [
            [0.000105, -0.000105],
            [0.003062, -0.003062],
            [0.011599, -0.011599],
            [0.005208, -0.005208]
        ],
        [
            [0.02, -0.02],
            [0.03, -0.03],
            [0.04, -0.04],
            [0.05, -0.05]
        ],
        [
            [-0.1, 0.1],
            [-0.2, 0.2],
            [0.3, -0.3],
            [-0.4, 0.4]
        ]
    ]
)

print(arr.shape)  # (2, 4, 2) or (number of samples, number of features, number of classes)

(3, 4, 2)


In [50]:
arr[1]

array([[ 0.02, -0.02],
       [ 0.03, -0.03],
       [ 0.04, -0.04],
       [ 0.05, -0.05]])

In [51]:
arr[1][1]

array([ 0.03, -0.03])

In [52]:
arr[1][1][1]

np.float64(-0.03)

In [53]:
arrIndices = np.arange(
    arr.shape[1]
).reshape(
    -1,
    1
)
print(arrIndices)

[[0]
 [1]
 [2]
 [3]]


In [54]:
arrtemp = arr[0]
print(arrtemp.reshape(-1, 1))


np.hstack(
    (
        arrIndices, 
        arrtemp # Ensure arrSHAPItem is also 2D for hstack
    )
)


[[ 0.000105]
 [-0.000105]
 [ 0.003062]
 [-0.003062]
 [ 0.011599]
 [-0.011599]
 [ 0.005208]
 [-0.005208]]


array([[ 0.0000e+00,  1.0500e-04, -1.0500e-04],
       [ 1.0000e+00,  3.0620e-03, -3.0620e-03],
       [ 2.0000e+00,  1.1599e-02, -1.1599e-02],
       [ 3.0000e+00,  5.2080e-03, -5.2080e-03]])

In [59]:
arrIndices = np.arange(
    arr.shape[1]
).reshape(
    -1,
    1
)
arrtemp = arr[2]
arrtempindexed = np.hstack(
    (
        arrIndices, 
        arrtemp # Ensure arrSHAPItem is also 2D for hstack
    )
)

print(arrtemp)
print()
print(
    arrtempindexed[np.argsort(arrtempindexed[:, 1])]
)
print()
print(arrtempindexed[np.argsort(arrtempindexed[:, 1])][2][0])

[[-0.1  0.1]
 [-0.2  0.2]
 [ 0.3 -0.3]
 [-0.4  0.4]]

[[ 3.  -0.4  0.4]
 [ 1.  -0.2  0.2]
 [ 0.  -0.1  0.1]
 [ 2.   0.3 -0.3]]

0.0


In [2]:
import Modelling_Class
import joblib

objPipeline = joblib.load('New_Churn_Pred_Model_With_SHAP.pkl')

for key,val in objPipeline.named_steps.items():
    print(f'{key} : {val}')

KeyboardInterrupt: 

In [20]:
lst = [1, 2, 3, 4]
num = int(''.join(map(str, lst)))
print(num)  # Output: 1234


1234
